version: "3.8"

services:
  scp-sl-server:
    image: ninepiece2/scp-secret-laboratory-docker-server:latest
    container_name: scp-sl-server
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
    environment:
      SERVERNAME: "My SCP Server"
      SERVERPORT: 7777
      MINPLAYERS: 2
    volumes:
      - ./SCP-SL:/home/steam/SCP-Secret-Laboratory
    restart: unless-stopped
    #user: "1000:1000"  # Optional: match host UID/GID